//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClienteWSLibros.ServiceReferenceLibros {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassLibrosExt", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ClassLibrosExt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorField;
        
        private System.Nullable<int> CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EditorialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EdicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClienteWSLibros.ServiceReferenceLibros.ClassCategoriasExt CategoriasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Autor {
            get {
                return this.AutorField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorField, value) != true)) {
                    this.AutorField = value;
                    this.RaisePropertyChanged("Autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((this.CategoriaField.Equals(value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Editorial {
            get {
                return this.EditorialField;
            }
            set {
                if ((object.ReferenceEquals(this.EditorialField, value) != true)) {
                    this.EditorialField = value;
                    this.RaisePropertyChanged("Editorial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Edicion {
            get {
                return this.EdicionField;
            }
            set {
                if ((object.ReferenceEquals(this.EdicionField, value) != true)) {
                    this.EdicionField = value;
                    this.RaisePropertyChanged("Edicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public WebClienteWSLibros.ServiceReferenceLibros.ClassCategoriasExt Categorias {
            get {
                return this.CategoriasField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriasField, value) != true)) {
                    this.CategoriasField = value;
                    this.RaisePropertyChanged("Categorias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassCategoriasExt", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ClassCategoriasExt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdC {
            get {
                return this.IdCField;
            }
            set {
                if ((this.IdCField.Equals(value) != true)) {
                    this.IdCField = value;
                    this.RaisePropertyChanged("IdC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreC {
            get {
                return this.NombreCField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCField, value) != true)) {
                    this.NombreCField = value;
                    this.RaisePropertyChanged("NombreC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceLibros.WebServiceLibrosSoap")]
    public interface WebServiceLibrosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Obtener", ReplyAction="*")]
        WebClienteWSLibros.ServiceReferenceLibros.ObtenerResponse Obtener(WebClienteWSLibros.ServiceReferenceLibros.ObtenerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Obtener", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClienteWSLibros.ServiceReferenceLibros.ObtenerResponse> ObtenerAsync(WebClienteWSLibros.ServiceReferenceLibros.ObtenerRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerCategoriaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCategoria", ReplyAction="*")]
        WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaResponse ObtenerCategoria(WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaResponse> ObtenerCategoriaAsync(WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento l del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        WebClienteWSLibros.ServiceReferenceLibros.AgregarResponse Agregar(WebClienteWSLibros.ServiceReferenceLibros.AgregarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClienteWSLibros.ServiceReferenceLibros.AgregarResponse> AgregarAsync(WebClienteWSLibros.ServiceReferenceLibros.AgregarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento IdObtenerResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdObtener", ReplyAction="*")]
        WebClienteWSLibros.ServiceReferenceLibros.IdObtenerResponse IdObtener(WebClienteWSLibros.ServiceReferenceLibros.IdObtenerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdObtener", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClienteWSLibros.ServiceReferenceLibros.IdObtenerResponse> IdObtenerAsync(WebClienteWSLibros.ServiceReferenceLibros.IdObtenerRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento l del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Editar", ReplyAction="*")]
        WebClienteWSLibros.ServiceReferenceLibros.EditarResponse Editar(WebClienteWSLibros.ServiceReferenceLibros.EditarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Editar", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClienteWSLibros.ServiceReferenceLibros.EditarResponse> EditarAsync(WebClienteWSLibros.ServiceReferenceLibros.EditarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        void Eliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task EliminarAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento valor del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        WebClienteWSLibros.ServiceReferenceLibros.BuscarResponse Buscar(WebClienteWSLibros.ServiceReferenceLibros.BuscarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClienteWSLibros.ServiceReferenceLibros.BuscarResponse> BuscarAsync(WebClienteWSLibros.ServiceReferenceLibros.BuscarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Obtener", Namespace="http://tempuri.org/", Order=0)]
        public WebClienteWSLibros.ServiceReferenceLibros.ObtenerRequestBody Body;
        
        public ObtenerRequest() {
        }
        
        public ObtenerRequest(WebClienteWSLibros.ServiceReferenceLibros.ObtenerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerRequestBody {
        
        public ObtenerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClienteWSLibros.ServiceReferenceLibros.ObtenerResponseBody Body;
        
        public ObtenerResponse() {
        }
        
        public ObtenerResponse(WebClienteWSLibros.ServiceReferenceLibros.ObtenerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebClienteWSLibros.ServiceReferenceLibros.ClassLibrosExt[] ObtenerResult;
        
        public ObtenerResponseBody() {
        }
        
        public ObtenerResponseBody(WebClienteWSLibros.ServiceReferenceLibros.ClassLibrosExt[] ObtenerResult) {
            this.ObtenerResult = ObtenerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCategoria", Namespace="http://tempuri.org/", Order=0)]
        public WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaRequestBody Body;
        
        public ObtenerCategoriaRequest() {
        }
        
        public ObtenerCategoriaRequest(WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerCategoriaRequestBody {
        
        public ObtenerCategoriaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCategoriaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaResponseBody Body;
        
        public ObtenerCategoriaResponse() {
        }
        
        public ObtenerCategoriaResponse(WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCategoriaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebClienteWSLibros.ServiceReferenceLibros.ClassCategoriasExt[] ObtenerCategoriaResult;
        
        public ObtenerCategoriaResponseBody() {
        }
        
        public ObtenerCategoriaResponseBody(WebClienteWSLibros.ServiceReferenceLibros.ClassCategoriasExt[] ObtenerCategoriaResult) {
            this.ObtenerCategoriaResult = ObtenerCategoriaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Agregar", Namespace="http://tempuri.org/", Order=0)]
        public WebClienteWSLibros.ServiceReferenceLibros.AgregarRequestBody Body;
        
        public AgregarRequest() {
        }
        
        public AgregarRequest(WebClienteWSLibros.ServiceReferenceLibros.AgregarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebClienteWSLibros.ServiceReferenceLibros.ClassLibrosExt l;
        
        public AgregarRequestBody() {
        }
        
        public AgregarRequestBody(WebClienteWSLibros.ServiceReferenceLibros.ClassLibrosExt l) {
            this.l = l;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClienteWSLibros.ServiceReferenceLibros.AgregarResponseBody Body;
        
        public AgregarResponse() {
        }
        
        public AgregarResponse(WebClienteWSLibros.ServiceReferenceLibros.AgregarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AgregarResponseBody {
        
        public AgregarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IdObtenerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IdObtener", Namespace="http://tempuri.org/", Order=0)]
        public WebClienteWSLibros.ServiceReferenceLibros.IdObtenerRequestBody Body;
        
        public IdObtenerRequest() {
        }
        
        public IdObtenerRequest(WebClienteWSLibros.ServiceReferenceLibros.IdObtenerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IdObtenerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public IdObtenerRequestBody() {
        }
        
        public IdObtenerRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IdObtenerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IdObtenerResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClienteWSLibros.ServiceReferenceLibros.IdObtenerResponseBody Body;
        
        public IdObtenerResponse() {
        }
        
        public IdObtenerResponse(WebClienteWSLibros.ServiceReferenceLibros.IdObtenerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IdObtenerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebClienteWSLibros.ServiceReferenceLibros.ClassLibrosExt IdObtenerResult;
        
        public IdObtenerResponseBody() {
        }
        
        public IdObtenerResponseBody(WebClienteWSLibros.ServiceReferenceLibros.ClassLibrosExt IdObtenerResult) {
            this.IdObtenerResult = IdObtenerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Editar", Namespace="http://tempuri.org/", Order=0)]
        public WebClienteWSLibros.ServiceReferenceLibros.EditarRequestBody Body;
        
        public EditarRequest() {
        }
        
        public EditarRequest(WebClienteWSLibros.ServiceReferenceLibros.EditarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebClienteWSLibros.ServiceReferenceLibros.ClassLibrosExt l;
        
        public EditarRequestBody() {
        }
        
        public EditarRequestBody(WebClienteWSLibros.ServiceReferenceLibros.ClassLibrosExt l) {
            this.l = l;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClienteWSLibros.ServiceReferenceLibros.EditarResponseBody Body;
        
        public EditarResponse() {
        }
        
        public EditarResponse(WebClienteWSLibros.ServiceReferenceLibros.EditarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditarResponseBody {
        
        public EditarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Buscar", Namespace="http://tempuri.org/", Order=0)]
        public WebClienteWSLibros.ServiceReferenceLibros.BuscarRequestBody Body;
        
        public BuscarRequest() {
        }
        
        public BuscarRequest(WebClienteWSLibros.ServiceReferenceLibros.BuscarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string valor;
        
        public BuscarRequestBody() {
        }
        
        public BuscarRequestBody(string valor) {
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClienteWSLibros.ServiceReferenceLibros.BuscarResponseBody Body;
        
        public BuscarResponse() {
        }
        
        public BuscarResponse(WebClienteWSLibros.ServiceReferenceLibros.BuscarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebClienteWSLibros.ServiceReferenceLibros.ClassLibrosExt[] BuscarResult;
        
        public BuscarResponseBody() {
        }
        
        public BuscarResponseBody(WebClienteWSLibros.ServiceReferenceLibros.ClassLibrosExt[] BuscarResult) {
            this.BuscarResult = BuscarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceLibrosSoapChannel : WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceLibrosSoapClient : System.ServiceModel.ClientBase<WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap>, WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap {
        
        public WebServiceLibrosSoapClient() {
        }
        
        public WebServiceLibrosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceLibrosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLibrosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLibrosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClienteWSLibros.ServiceReferenceLibros.ObtenerResponse WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap.Obtener(WebClienteWSLibros.ServiceReferenceLibros.ObtenerRequest request) {
            return base.Channel.Obtener(request);
        }
        
        public WebClienteWSLibros.ServiceReferenceLibros.ClassLibrosExt[] Obtener() {
            WebClienteWSLibros.ServiceReferenceLibros.ObtenerRequest inValue = new WebClienteWSLibros.ServiceReferenceLibros.ObtenerRequest();
            inValue.Body = new WebClienteWSLibros.ServiceReferenceLibros.ObtenerRequestBody();
            WebClienteWSLibros.ServiceReferenceLibros.ObtenerResponse retVal = ((WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap)(this)).Obtener(inValue);
            return retVal.Body.ObtenerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClienteWSLibros.ServiceReferenceLibros.ObtenerResponse> WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap.ObtenerAsync(WebClienteWSLibros.ServiceReferenceLibros.ObtenerRequest request) {
            return base.Channel.ObtenerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClienteWSLibros.ServiceReferenceLibros.ObtenerResponse> ObtenerAsync() {
            WebClienteWSLibros.ServiceReferenceLibros.ObtenerRequest inValue = new WebClienteWSLibros.ServiceReferenceLibros.ObtenerRequest();
            inValue.Body = new WebClienteWSLibros.ServiceReferenceLibros.ObtenerRequestBody();
            return ((WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap)(this)).ObtenerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaResponse WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap.ObtenerCategoria(WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaRequest request) {
            return base.Channel.ObtenerCategoria(request);
        }
        
        public WebClienteWSLibros.ServiceReferenceLibros.ClassCategoriasExt[] ObtenerCategoria() {
            WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaRequest inValue = new WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaRequest();
            inValue.Body = new WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaRequestBody();
            WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaResponse retVal = ((WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap)(this)).ObtenerCategoria(inValue);
            return retVal.Body.ObtenerCategoriaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaResponse> WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap.ObtenerCategoriaAsync(WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaRequest request) {
            return base.Channel.ObtenerCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaResponse> ObtenerCategoriaAsync() {
            WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaRequest inValue = new WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaRequest();
            inValue.Body = new WebClienteWSLibros.ServiceReferenceLibros.ObtenerCategoriaRequestBody();
            return ((WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap)(this)).ObtenerCategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClienteWSLibros.ServiceReferenceLibros.AgregarResponse WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap.Agregar(WebClienteWSLibros.ServiceReferenceLibros.AgregarRequest request) {
            return base.Channel.Agregar(request);
        }
        
        public void Agregar(WebClienteWSLibros.ServiceReferenceLibros.ClassLibrosExt l) {
            WebClienteWSLibros.ServiceReferenceLibros.AgregarRequest inValue = new WebClienteWSLibros.ServiceReferenceLibros.AgregarRequest();
            inValue.Body = new WebClienteWSLibros.ServiceReferenceLibros.AgregarRequestBody();
            inValue.Body.l = l;
            WebClienteWSLibros.ServiceReferenceLibros.AgregarResponse retVal = ((WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap)(this)).Agregar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClienteWSLibros.ServiceReferenceLibros.AgregarResponse> WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap.AgregarAsync(WebClienteWSLibros.ServiceReferenceLibros.AgregarRequest request) {
            return base.Channel.AgregarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClienteWSLibros.ServiceReferenceLibros.AgregarResponse> AgregarAsync(WebClienteWSLibros.ServiceReferenceLibros.ClassLibrosExt l) {
            WebClienteWSLibros.ServiceReferenceLibros.AgregarRequest inValue = new WebClienteWSLibros.ServiceReferenceLibros.AgregarRequest();
            inValue.Body = new WebClienteWSLibros.ServiceReferenceLibros.AgregarRequestBody();
            inValue.Body.l = l;
            return ((WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap)(this)).AgregarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClienteWSLibros.ServiceReferenceLibros.IdObtenerResponse WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap.IdObtener(WebClienteWSLibros.ServiceReferenceLibros.IdObtenerRequest request) {
            return base.Channel.IdObtener(request);
        }
        
        public WebClienteWSLibros.ServiceReferenceLibros.ClassLibrosExt IdObtener(int id) {
            WebClienteWSLibros.ServiceReferenceLibros.IdObtenerRequest inValue = new WebClienteWSLibros.ServiceReferenceLibros.IdObtenerRequest();
            inValue.Body = new WebClienteWSLibros.ServiceReferenceLibros.IdObtenerRequestBody();
            inValue.Body.id = id;
            WebClienteWSLibros.ServiceReferenceLibros.IdObtenerResponse retVal = ((WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap)(this)).IdObtener(inValue);
            return retVal.Body.IdObtenerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClienteWSLibros.ServiceReferenceLibros.IdObtenerResponse> WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap.IdObtenerAsync(WebClienteWSLibros.ServiceReferenceLibros.IdObtenerRequest request) {
            return base.Channel.IdObtenerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClienteWSLibros.ServiceReferenceLibros.IdObtenerResponse> IdObtenerAsync(int id) {
            WebClienteWSLibros.ServiceReferenceLibros.IdObtenerRequest inValue = new WebClienteWSLibros.ServiceReferenceLibros.IdObtenerRequest();
            inValue.Body = new WebClienteWSLibros.ServiceReferenceLibros.IdObtenerRequestBody();
            inValue.Body.id = id;
            return ((WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap)(this)).IdObtenerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClienteWSLibros.ServiceReferenceLibros.EditarResponse WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap.Editar(WebClienteWSLibros.ServiceReferenceLibros.EditarRequest request) {
            return base.Channel.Editar(request);
        }
        
        public void Editar(WebClienteWSLibros.ServiceReferenceLibros.ClassLibrosExt l) {
            WebClienteWSLibros.ServiceReferenceLibros.EditarRequest inValue = new WebClienteWSLibros.ServiceReferenceLibros.EditarRequest();
            inValue.Body = new WebClienteWSLibros.ServiceReferenceLibros.EditarRequestBody();
            inValue.Body.l = l;
            WebClienteWSLibros.ServiceReferenceLibros.EditarResponse retVal = ((WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap)(this)).Editar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClienteWSLibros.ServiceReferenceLibros.EditarResponse> WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap.EditarAsync(WebClienteWSLibros.ServiceReferenceLibros.EditarRequest request) {
            return base.Channel.EditarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClienteWSLibros.ServiceReferenceLibros.EditarResponse> EditarAsync(WebClienteWSLibros.ServiceReferenceLibros.ClassLibrosExt l) {
            WebClienteWSLibros.ServiceReferenceLibros.EditarRequest inValue = new WebClienteWSLibros.ServiceReferenceLibros.EditarRequest();
            inValue.Body = new WebClienteWSLibros.ServiceReferenceLibros.EditarRequestBody();
            inValue.Body.l = l;
            return ((WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap)(this)).EditarAsync(inValue);
        }
        
        public void Eliminar(int id) {
            base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task EliminarAsync(int id) {
            return base.Channel.EliminarAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClienteWSLibros.ServiceReferenceLibros.BuscarResponse WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap.Buscar(WebClienteWSLibros.ServiceReferenceLibros.BuscarRequest request) {
            return base.Channel.Buscar(request);
        }
        
        public WebClienteWSLibros.ServiceReferenceLibros.ClassLibrosExt[] Buscar(string valor) {
            WebClienteWSLibros.ServiceReferenceLibros.BuscarRequest inValue = new WebClienteWSLibros.ServiceReferenceLibros.BuscarRequest();
            inValue.Body = new WebClienteWSLibros.ServiceReferenceLibros.BuscarRequestBody();
            inValue.Body.valor = valor;
            WebClienteWSLibros.ServiceReferenceLibros.BuscarResponse retVal = ((WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap)(this)).Buscar(inValue);
            return retVal.Body.BuscarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClienteWSLibros.ServiceReferenceLibros.BuscarResponse> WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap.BuscarAsync(WebClienteWSLibros.ServiceReferenceLibros.BuscarRequest request) {
            return base.Channel.BuscarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClienteWSLibros.ServiceReferenceLibros.BuscarResponse> BuscarAsync(string valor) {
            WebClienteWSLibros.ServiceReferenceLibros.BuscarRequest inValue = new WebClienteWSLibros.ServiceReferenceLibros.BuscarRequest();
            inValue.Body = new WebClienteWSLibros.ServiceReferenceLibros.BuscarRequestBody();
            inValue.Body.valor = valor;
            return ((WebClienteWSLibros.ServiceReferenceLibros.WebServiceLibrosSoap)(this)).BuscarAsync(inValue);
        }
    }
}
